serviceProperties :
    serviceDataProperties:
        serviceGroupName : "aggregation"
        serviceName : "aggregation_1"
        ip : "localhost"
        port : 8084
        rootUrl : "/aggregation"
        topicInfo : "{\"consumers\":{\"aggregationTopic\":[\"aggregationTopic_1\"]}}"
    zNodeInfoProperties:
        regZnodePath : "/regManageNode"
        regZnodeChildPath : "/regManageNode/regManageChildNode"
        depZnodePath : "/depManageNode"
        zookeeperHostport : "192.168.56.17:2181"
    kafkaProperties:
        consumers:
            aggregationTopic_1:
                brokerList : "192.168.56.17:9092"
                consumerTopic : "aggregationTopic_1"
                groupId : "aggregationTopic"
                deserializerClass : "org.apache.kafka.common.serialization.StringDeserializer"

tomcatPort : 8084

endpoints.shutdown.enabled : true