serviceProperties :
    serviceDataProperties:
        serviceGroupName : "aggregation"
        serviceName : "aggregation_standalone"
        ip : "172.18.0.81"
        port : 8131
        rootUrl : "/aggregation"
        topicInfo : "{\"consumers\":{\"aggregationTopic\":[\"aggregationTopic_1\"]}}"
    zNodeInfoProperties:
        confZnodePath : "/confManageNode"
        regZnodePath : "/regManageNode"
        regZnodeChildPath : "/regManageNode/regManageChildNode"
        depZnodePath : "/depManageNode"
        zookeeperHostport : "172.18.0.11:2191"


tomcatPort : 8131

logging.file : "/opt/aggregation/log/console.log"